#!/usr/bin/env python3
"""Exploratory range dumps: upload a range-specific payload and dump EPS memory.

Five fixed ranges beyond the production DataFlash window, for mapping parts of the
EPS nobody has read yet (code flash, the space above it, RAM, and two wider
DataFlash windows). Each range is a separate 4096-byte payload with the range baked
into four 16-bit shellcode immediates; the driver here only has to know the matching
start/end, so a profile is just (payload, start, end, sha256).

Vehicle requirement: Not Ready to Drive mode (not READY Mode), same as the
production dump. Keeping the comma powered so the panda doesn't cold-cycle gives a
complete dump on the first run.

UNPROVEN. These payloads have never run on a car. They are generated by
Sienna2024Comma notes/tools/make_payloads.py, which verifies each one decrypts to
crc32 == 0xffffffff with a valid CMAC and that the patched immediates read back as
the requested range — but no end-to-end control exists. Treat a null result as
"unknown", not as evidence about the part.

This mirrors the UDS session preamble in dump_dataflash.py by deliberate duplication
rather than a shared helper, matching the existing split between that module and
extractor.py: the production path stays untouched by anything done here.
"""
import hashlib
import struct
import subprocess
import time
from datetime import datetime
from pathlib import Path

from tsk.lib.env import is_agnos, RANGE_DUMP_DIR
from tsk.lib.extractor import NotAGNOSError, RetryError, TSKExtractor

# EPS UDS parameters (shared with the extractor and the production dump)
ADDR = TSKExtractor.ADDR  # 0x7a1
BUS = TSKExtractor.BUS    # 0

# Payload upload/trigger vector. Identical to dump_dataflash.dump(); only the
# payload bytes and the dump range differ between profiles.
PAYLOAD_LOAD_ADDR = 0xFEBF0000
PAYLOAD_LOAD_SIZE = 0x1000
TRIGGER_ADDR = 0x000E0000
TRIGGER_SIZE = 0x8000

# Frame collection timing. MAX_SECONDS is a hard per-run ceiling (Calvin: 5 minutes
# for every profile regardless of size); IDLE_TIMEOUT is what normally ends a run,
# since the EPS stops emitting once it walks off the end of its range.
IDLE_TIMEOUT = 10.0
MAX_SECONDS = 300.0
RESPONSE_PENDING = b"\x03\x7f\x31\x78\x00\x00\x00\x00"

# The payload lives at PAYLOAD_LOAD_ADDR and its CRC extent covers 0xFEBF0000-
# 0xFEBF0FF0, so any range containing that span reads the payload back instead of
# the original contents. Only the `ram` profile overlaps.
PAYLOAD_CLOBBER_START = 0xFEBF0000
PAYLOAD_CLOBBER_END = 0xFEBF0FF0


class Profile:
  def __init__(self, key, label, filename, sha256, start, end, note=""):
    self.key = key
    self.label = label
    self.filename = filename
    self.sha256 = sha256
    self.start = start
    self.end = end
    self.note = note

  @property
  def total(self) -> int:
    return self.end - self.start

  @property
  def frames(self) -> int:
    return self.total // 4

  @property
  def payload_path(self) -> str:
    return str(Path(__file__).parent / self.filename)

  def clobber_span(self):
    """(offset, length) of the payload's own footprint inside this range, or None."""
    lo = max(self.start, PAYLOAD_CLOBBER_START)
    hi = min(self.end, PAYLOAD_CLOBBER_END)
    if lo >= hi:
      return None
    return lo - self.start, hi - lo


# Ranges and rationale: Sienna2024Comma notes/tools/payloads/README.md.
PROFILES = {
  p.key: p for p in (
    Profile(
      "codeflash", "Code flash",
      "payload_codeflash_00000000_00100000.bin",
      "7b2983f631aa46aeeed8ce167231d36c00af39fcf7a74d53729e008b666c53ea",
      0x00000000, 0x00100000,
      "Code flash on R7F701381EAFP is 1 MB.",
    ),
    Profile(
      "above_codeflash", "Above code flash",
      "payload_above_codeflash_00100000_00200000.bin",
      "ef9be4a572f61afd434ada831a6be313a3878f387b00816b5716b9c15036feb5",
      0x00100000, 0x00200000,
      "Separate file so the 0x00100000 boundary is a file boundary, not buried mid-dump.",
    ),
    Profile(
      "ram", "RAM",
      "payload_ram_febc0000_fec20000.bin",
      "9dfde88595ba7ab025137e4338a6ff8b93acca10344783aee48e039a4d50d953",
      0xFEBC0000, 0xFEC20000,
      "RAM is 192 KB but its base address is unsourced; this window is a superset.",
    ),
    Profile(
      "dataflash", "DataFlash 64K",
      "payload_dataflash_ff200000_ff210000.bin",
      "9545c4192797a4800d675c454892a787f1df88683522eefb6b47915cf9c7a4eb",
      0xFF200000, 0xFF210000,
      "64 KB, not the 32 KB of R7F701381E. Unmapped space returns zeros.",
    ),
    Profile(
      "dataflash_wide", "DataFlash wide",
      "payload_dataflash_wide_ff200000_ff238000.bin",
      "e001776a1fb829222a566f216f93870a1b99207a353ad0e48e234266130afdde",
      0xFF200000, 0xFF238000,
      "224 KB — every DataFlash size in the notes except 672 KB.",
    ),
  )
}

PROFILE_KEYS = tuple(PROFILES.keys())


def profile_for(key):
  return PROFILES.get(key)


def dump_dir() -> Path:
  return Path(RANGE_DUMP_DIR)


def dump_filename(profile, stamp: str) -> str:
  return f"dump_{profile.key}_{profile.start:08x}_{profile.end:08x}_{stamp}.bin"


def list_dumps(profile=None):
  """Persisted dumps, newest first. Filtered to one profile when given."""
  try:
    entries = sorted(dump_dir().iterdir())
  except OSError:
    return []
  out = []
  for path in entries:
    if path.suffix != ".bin" or not path.name.startswith("dump_"):
      continue
    if profile is not None and not path.name.startswith(f"dump_{profile.key}_"):
      continue
    try:
      size = path.stat().st_size
    except OSError:
      continue
    out.append({"name": path.name, "path": str(path), "bytes": size})
  out.reverse()
  return out


def _noop(**kwargs) -> None:
  pass


def _finalize(profile, dump_buf, frames_count, bytes_received, stamp) -> dict:
  """Classify a finished collection and persist it. Pure apart from the file write.

  Unlike the production dump there is no key-window gate: KNOWN_KEY_OFFSET is
  meaningful only for the DataFlash-at-0xFF200000 layout, and for code flash or RAM
  a partial capture is still the data being sought. So every run that returned at
  least one frame is written, and the caller decides whether it answered anything.
  """
  status = "complete" if bytes_received >= profile.total else "partial"

  if frames_count == 0:
    return {
      "status": "empty",
      "frames": 0,
      "bytes": 0,
      "total": profile.total,
      "dump_path": "",
      "message": ("No frames received.\nThe payload did not run, or the EPS did not "
                  "reach the dump loop.\nRestart the car into Not Ready To Drive mode "
                  "and try again."),
    }

  path = dump_dir() / dump_filename(profile, stamp)
  path.parent.mkdir(parents=True, exist_ok=True)
  path.write_bytes(bytes(dump_buf))

  if status == "complete":
    message = f"Dump complete: {bytes_received}/{profile.total} bytes.\n{path.name}"
  else:
    pct = bytes_received * 100.0 / profile.total if profile.total else 0.0
    message = (f"Partial dump: {bytes_received}/{profile.total} bytes ({pct:.1f}%).\n"
               f"Saved anyway — gaps read as zero.\n{path.name}")

  clobber = profile.clobber_span()
  if clobber is not None:
    off, length = clobber
    message += (f"\nNote: {length} bytes at offset 0x{off:x} are the payload itself, "
                "not the original contents.")

  return {
    "status": status,
    "frames": frames_count,
    "bytes": bytes_received,
    "total": profile.total,
    "dump_path": str(path),
    "message": message,
  }


def dump(profile_key, progress_cb=None) -> dict:
  """Upload the profile's payload and dump its range from the EPS.

  progress_cb, if given, is called as
    progress_cb(status=, frames=, bytes_done=, total=, message=)
  with whichever keys changed. Returns a dict:
    {status, frames, bytes, total, dump_path, message}
  where status is one of: complete | partial | empty | failed.
  Raises NotAGNOSError off-device.
  """
  profile = PROFILES.get(profile_key)
  if profile is None:
    raise RetryError(f"Unknown dump profile: {profile_key}")

  if not is_agnos():
    raise NotAGNOSError

  cb = progress_cb or _noop
  stamp = datetime.now().strftime("%Y%m%d-%H%M%S")

  from Crypto.Cipher import AES

  from opendbc.car.isotp import isotp_send
  from opendbc.car.structs import CarParams
  from opendbc.car.uds import UdsClient, ACCESS_TYPE, SESSION_TYPE, SERVICE_TYPE, \
    ROUTINE_CONTROL_TYPE, InvalidServiceIdError, MessageTimeoutError, NegativeResponseError

  # Verify the payload before touching the car.
  payload = Path(profile.payload_path).read_bytes()
  if hashlib.sha256(payload).hexdigest() != profile.sha256:
    raise RetryError(f"{profile.label} payload SHA256 mismatch")
  if len(payload) != PAYLOAD_LOAD_SIZE:
    raise RetryError(f"{profile.label} payload wrong size")

  cb(status="running", frames=0, bytes_done=0, total=profile.total, message="")

  # Kill the manager so it doesn't restart pandad mid-dump (mirrors extractor.hack()).
  subprocess.run(["pkill", "-9", "-f", "manager.py"], check=False)
  subprocess.run(["pkill", "-9", "-f", "pandad"], check=False)
  time.sleep(2)

  panda = TSKExtractor._connect_panda()
  panda.set_safety_mode(CarParams.SafetyModel.elm327)

  uds = UdsClient(panda, ADDR, ADDR + 8, BUS, timeout=0.1, response_pending_timeout=0.1)

  # Mandatory programming-session flow, timing identical to the production dump.
  try:
    uds.diagnostic_session_control(SESSION_TYPE.DEFAULT)
    time.sleep(0.5)
    uds.diagnostic_session_control(SESSION_TYPE.EXTENDED_DIAGNOSTIC)
    time.sleep(0.7)
    uds.diagnostic_session_control(SESSION_TYPE.PROGRAMMING)
    time.sleep(1.0)
    uds.diagnostic_session_control(SESSION_TYPE.PROGRAMMING)
  except (InvalidServiceIdError, MessageTimeoutError, NegativeResponseError):
    raise RetryError("Can't enter programming session.")

  # Security access.
  try:
    seed_payload = b"\x00" * 16
    seed = uds.security_access(ACCESS_TYPE.REQUEST_SEED, data_record=seed_payload)
    key = AES.new(TSKExtractor.SEED_KEY_SECRET, AES.MODE_ECB).decrypt(seed_payload)
    key = AES.new(key, AES.MODE_ECB).encrypt(seed)
    uds.security_access(ACCESS_TYPE.SEND_KEY, key)
  except (InvalidServiceIdError, MessageTimeoutError, NegativeResponseError):
    raise RetryError("Security Access failed")

  # Upload and verify the payload.
  try:
    uds.write_data_by_identifier(0x203, b"\x00" * 5)
    uds.write_data_by_identifier(0x201, TSKExtractor.DID_201_KEY)
    uds.write_data_by_identifier(0x202, TSKExtractor.DID_202_IV)

    request = b"\x01\x46\x01\x00" + struct.pack("!I", PAYLOAD_LOAD_ADDR) + struct.pack("!I", PAYLOAD_LOAD_SIZE)
    uds._uds_request(SERVICE_TYPE.REQUEST_DOWNLOAD, data=request)

    chunk_size = 0x400
    for i in range(len(payload) // chunk_size):
      uds.transfer_data(i + 1, payload[i * chunk_size:(i + 1) * chunk_size])
    uds.request_transfer_exit()

    verify = b"\x45\x00" + struct.pack("!I", PAYLOAD_LOAD_ADDR) + struct.pack("!I", PAYLOAD_LOAD_SIZE)
    uds.routine_control(ROUTINE_CONTROL_TYPE.START, 0x10f0, verify)
  except (InvalidServiceIdError, MessageTimeoutError, NegativeResponseError):
    raise RetryError("Payload upload failed")

  # Trigger the payload via the erase routine. Send manually so we don't block
  # waiting for a response that never comes. Same vector as extractor.hack().
  erase = b"\x31\x01\xff\x00" + b"\x45\x00" + struct.pack("!I", TRIGGER_ADDR) + struct.pack("!I", TRIGGER_SIZE)
  isotp_send(panda, erase, ADDR, bus=BUS)

  # Collect dump frames. Each frame carries a 24-bit pointer (low 3 bytes of the
  # address) plus 4 data bytes; the top address byte comes from the profile start.
  # Every profile range sits inside one 16 MB top-byte window, so no aliasing.
  top_byte = profile.start & 0xFF000000
  dump_buf = bytearray(profile.total)
  received = bytearray(profile.total)
  frames_count = 0
  bytes_covered = 0
  begin = time.time()
  last_progress = begin

  while True:
    if time.time() - begin > MAX_SECONDS:
      break

    made_progress = False
    for addr, *_, data, bus in panda.can_recv():
      if bus != BUS or addr != ADDR + 8 or len(data) < 8:
        continue
      if data == RESPONSE_PENDING:
        continue

      ptr_low24 = (struct.unpack("<I", data[:4])[0] >> 8) & 0xFFFFFF
      offset = (top_byte | ptr_low24) - profile.start
      if offset < 0 or offset + 4 > profile.total:
        continue

      dump_buf[offset:offset + 4] = data[4:8]
      # Count only newly-covered bytes so a retransmitted or overlapping chunk isn't
      # double-counted.
      for k in range(offset, offset + 4):
        if received[k] == 0:
          received[k] = 1
          bytes_covered += 1
      frames_count += 1
      made_progress = True

      if frames_count % 256 == 0:
        cb(status="running", frames=frames_count, bytes_done=bytes_covered, total=profile.total)

    if made_progress:
      last_progress = time.time()
    elif time.time() - last_progress > IDLE_TIMEOUT:
      break
    else:
      time.sleep(0.001)

    if bytes_covered >= profile.total:
      break

  bytes_received = bytes_covered
  cb(status="running", frames=frames_count, bytes_done=bytes_received, total=profile.total)
  return _finalize(profile, dump_buf, frames_count, bytes_received, stamp)
